---
- name: Instal·lació de servei DHCP
  hosts: your_dhcp_servers
  become: true
  vars:
    dhcp_config_files_path: "/home/risso/"

  tasks:
    - name: Copiem els arxius de configuració de DHCP
      copy:
        src: "{{ dhcp_config_files_path }}"
        dest: "/etc/dhcp/"
        owner: root
        group: root
        mode: '0644'

    - name: Instal·lació de isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Fer start al servei
      service:
        name: isc-dhcp-server
        state: started