--- 
- hosts: centos 
  remote_user: risso 
  tasks: 

  - name: Decarreguem la imatge de Nagios 
    get_url: 
      url: http://assets.nagios.com/downloads/nagiosxi/xi-latest.tar.gz 
      dest: "/tmp/xi-latest.tar.gz" 
      force: yes 
      validate_certs: no 

  - name: Descomprimim paquet nagios 
    unarchive: 
      src: "/tmp/xi-latest.tar.gz" 
      dest: "/tmp/" 
      copy: no

  - name: Executem l’script d’instal·lació (-n tracta de fer la instal·lació unnattended)
    shell: "./fullinstall -n" 
    args: 
      chdir: "/tmp/nagiosxi" 
