---
- hosts: centos
  remote_user: risso
  tasks:

  - name: Download latest XI source
    get_url:
      url: http://assets.nagios.com/downloads/nagiosxi/xi-latest.tar.gz
      dest: "/tmp/xi-latest.tar.gz"
      force: yes
      validate_certs: no

  - name: Untar source tarball
    unarchive:
      src: "/tmp/xi-latest.tar.gz"
      dest: "/tmp/"
      copy: no

  - name: Run install
    shell: "./fullinstall -n"
    args:
      chdir: "/tmp/nagiosxi"
